#include <errno.h>
#include <error.h>
#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <linux/input.h>
#include <linux/uinput.h>
#include <sys/ioctl.h>

/* Absolute path to the file that contains a list of all registered 
 * input devices */
#define DEVICE_INPUT_PATH "/proc/bus/input/devices"

/* Absolute path to the directory that contains real-time input events 
 * generated by the kernel's evdev (event device) subsystem */
#define DEVICE_EVENT_PATH "/dev/input/"

/* Absolute path to the file that allows to create a virtual device */
#define VIRTUAL_DEVICE_PATH "/dev/uinput"

#define MAX_DEVICES 16       /* Maximum number of devices supported in 
                              * parallel */
#define DEVICE_NAME_SIZE 128 /* Maximum number of character in a device name */
#define EVENT_BUFFER_SIZE 64 /* Maximum number of events int the buffer */

/* Represent the default weight applied to a stream of data for the 
 * smoothing algorithm */
#define DEFAULT_SMOOTH_RATE 0.80

/* Bitmask for activation actions */
#define ACTION_ALWAYS       (1 << 0)
#define ACTION_LEFT_CLICK   (1 << 1)
#define ACTION_MIDDLE_CLICK (1 << 2)
#define ACTION_RIGHT_CLICK  (1 << 3)
#define ACTION_ON_TOUCH     (1 << 4)

/* Return 1 if the action 'list' contains action 'action', 0 otherwise */
#define HAS_ACTION(list, action) (((list) & (action)) != 0)

/* Number of bits in a single unsigned long integer */
#define BITS_PER_LONG (sizeof(unsigned long) * 8)

/* Determine the number of unsigned long elements required to hold 'x' bits */
#define NBITS(x) (((x) - 1)/BITS_PER_LONG+1)

/* Return 1 if the specified 'bit' is set in the 'array', 0 otherwise */
#define TEST_BIT(bit, array) \
    ((array[(bit) / BITS_PER_LONG] >> ((bit) % BITS_PER_LONG)) & 1)

/* Represent an active device in the evdev */
struct dev {
    char name[DEVICE_NAME_SIZE]; /* Name of the device */
    int fd; /* Event handler file descriptor associated to the device */
};

/* Represent the state of the instance of the program. */
struct smice {
    const char *progname;                /* Null-term program name string */
    struct dev phy_devices[MAX_DEVICES]; /* File descriptors of physical
                                          * devices */
    struct dev vir_devices[MAX_DEVICES]; /* File descriptors of virtual
                                          * devices */
    struct dev_event {
        struct input_event event; /* Event */
        int dev_index;            /* Index of the device in 'phy_devices' 
                                   * array that generates the event */
    } event_buf[EVENT_BUFFER_SIZE]; /* Buffer of events generated by the
                                     * physical devices */
    struct dev_pos {
        double x;
        double y;
        int is_init; /* Flag to track initialization state for absolute
                      * coordinate. 
                      * 0 (finger/per lifted) if the device position will 
                      * snap directly to the raw hardware input
                      * 1 if the device position is part of an history 
                      * position state */
    } device_pos[MAX_DEVICES];      /* Track the average history value of 
                                     * positions for each device */

    float smooth_rate; /* [0.0,1.0] weight applied to the stream of data 
                        * for the smoothing algorithm */
    uint32_t config_actions; /* Bitmap of user-selected trigger actions */
    uint32_t active_actions; /* Bitmap of current trigger actions */
} smice;

static volatile int running = 1;

/* Catch the signal from the program and set 'running' to 0. */
void sigHandler(int signum) {
    (void)signum;
    running = 0;
}

/* Search for all the registered pointinga devices (mice, trackpads, tablets) 
 * and fills the `devices` array for each of them.
 * The search ends when no more new devices are found or when 'max_devices' 
 * devices have been found.
 * Return the number of devices found or -1 if an error occurs.
 * It's up to the caller to close the open file descriptors. */
int getPointerDevices(struct dev *devices, int max_devices) {
    FILE *fp = fopen(DEVICE_INPUT_PATH, "r");
    if (fp == NULL) {
        perror("Failed to open " DEVICE_INPUT_PATH);
        return -1;
    }

    /* Read the devices file to search for the following pattern:
     *   N: Name="..."
     *   H: Handlers=mouseX eventY
     * where X and Y are intergers that indicate the mouse and its 
     * associated event handler rispectively. */
    char line[512];
    int count = 0;
    char devname[DEVICE_NAME_SIZE];
    while (fgets(line, sizeof(line), fp) && count < max_devices) {
        if (strncmp(line, "N: Name=\"", 9) == 0) {
            strncpy(devname, line+9, sizeof(devname));
            devname[sizeof(devname)-1] = '\0'; 

            /* Erase terminating " or \n char */
            char *c;
            if      ((c = strchr(devname, '\"')) != NULL) *c = '\0';
            else if ((c = strchr(devname, '\n')) != NULL) *c = '\0';
        }

        if (strncmp(line, "H: Handlers=", 12) == 0) {
            char *evstr = strstr(line, "event");
            if (evstr != NULL) {
                /* Get the event handler file of the device */
                int evnum = atoi(evstr+5);
                char event_path[64];
                snprintf(event_path, sizeof(event_path), "%sevent%d", 
                         DEVICE_EVENT_PATH, evnum);

                int fd;
                if ((fd = open(event_path, O_RDONLY | O_NONBLOCK)) == -1) {
                    error(0, errno, "Failed to open %s", event_path);
                    goto efile_err;
                }

                /* Query the device capabilities to check if it's a cursor
                 * controller */
                unsigned long ev_bits[NBITS(EV_MAX)] = {0};
                int is_pointer = 0;

                if (ioctl(fd, EVIOCGBIT(0, sizeof(ev_bits)), ev_bits) >= 0) {
                    /* Check for relative pointer */
                    if (TEST_BIT(EV_REL, ev_bits)) {
                        unsigned long rel_bits[NBITS(REL_MAX)] = {0};
                        ioctl(fd, EVIOCGBIT(EV_REL, sizeof(rel_bits)), 
                              rel_bits);
                        if (TEST_BIT(REL_X, rel_bits) && 
                            TEST_BIT(REL_Y, rel_bits)) is_pointer = 1;
                    }
                    /* Check for absolute pointer */
                    if (!is_pointer && TEST_BIT(EV_ABS, ev_bits)) {
                        unsigned long abs_bits[NBITS(ABS_MAX)] = {0};
                        ioctl(fd, EVIOCGBIT(EV_ABS, sizeof(abs_bits)),
                              abs_bits);
                        if (TEST_BIT(ABS_X, abs_bits) && 
                            TEST_BIT(ABS_Y, abs_bits)) is_pointer = 1;
                    }
                }

                if (!is_pointer) {
                    devname[0] = '\0';
                    close(fd);
                    continue;
                }

                struct dev *device = &devices[count];
                strncpy(device->name, devname, sizeof(device->name));
                device->name[sizeof(device->name)-1] = '\0';
                device->fd = fd;
                devname[0] = '\0';

                count++;
            }
        }
    }

    fclose(fp);
    return count;

efile_err:
    for (int j = 0; j < count; j++) {
        close(devices[j].fd);
    }

    return -1;
}

/* Create 'count' virtual devices that clone the capabilities of the 
 * 'count' 'src_devices'.
 * Return 1 on success, 0 otherwise.
 * It's up to the caller to destroy the created virtual devices. */
int createVirtualDevices(struct dev *dst_devices, struct dev *src_devices, 
                         int count) 
{
    struct uinput_setup usetup;

    int i;
    for (i = 0; i < count; i++) {
        int src_fd = src_devices[i].fd;
        int fd = open(VIRTUAL_DEVICE_PATH, O_WRONLY | O_NONBLOCK);
        if (fd == -1) {
            perror("Failed to open " VIRTUAL_DEVICE_PATH);
            goto vdev_err;
        }

        /* Fetch main event types supported by the physical hardware */
        unsigned long ev_bits[NBITS(EV_MAX)] = {0};
        if (ioctl(src_fd, EVIOCGBIT(0, sizeof(ev_bits)), ev_bits) == -1) {
            perror("ioctl EVIOCGBIT failed");
            close(fd);
            goto vdev_err;
        }

        /* Clone buttons and keys */
        if (TEST_BIT(EV_KEY, ev_bits)) {
            ioctl(fd, UI_SET_EVBIT, EV_KEY);
            unsigned long key_bits[NBITS(KEY_MAX)] = {0};
            ioctl(src_fd, EVIOCGBIT(EV_KEY, sizeof(key_bits)), key_bits);
            for (int k = 0; k < KEY_MAX; k++) {
                if (TEST_BIT(k, key_bits)) {
                    ioctl(fd, UI_SET_KEYBIT, k);
                }
            }
        }

        /* Clone relative axis */
        if (TEST_BIT(EV_REL, ev_bits)) {
            ioctl(fd, UI_SET_EVBIT, EV_REL);
            unsigned long rel_bits[NBITS(REL_MAX)] = {0};
            ioctl(src_fd, EVIOCGBIT(EV_REL, sizeof(rel_bits)), rel_bits);
            for (int r = 0; r < REL_MAX; r++) {
                if (TEST_BIT(r, rel_bits)) {
                    ioctl(fd, UI_SET_RELBIT, r);
                }
            }
        }

        /* Clone absolute axis */
        if (TEST_BIT(EV_ABS, ev_bits)) {
            ioctl(fd, UI_SET_EVBIT, EV_ABS);
            unsigned long abs_bits[NBITS(ABS_MAX)] = {0};
            ioctl(src_fd, EVIOCGBIT(EV_ABS, sizeof(abs_bits)), abs_bits);
            for (int a = 0; a < ABS_MAX; a++) {
                if (TEST_BIT(a, abs_bits)) {
                    ioctl(fd, UI_SET_ABSBIT, a);

                    /* Important: Absolute devices must sync dimensions 
                     * with the kernel */
                    struct uinput_abs_setup abs_setup;
                    memset(&abs_setup, 0, sizeof(abs_setup));
                    abs_setup.code = a;
                    if (ioctl(src_fd, EVIOCGABS(a), &abs_setup.absinfo) >= 0) {
                        ioctl(fd, UI_ABS_SETUP, &abs_setup);
                    }
                }
            }
        }

        /* Configure device properties */
        memset(&usetup, 0, sizeof(usetup));
        usetup.id.bustype = BUS_USB;
        usetup.id.vendor  = 0xCAFE;      /* sample vendor ID */
        usetup.id.product = 0x0001 + i; /* unique product ID */
        snprintf(usetup.name, sizeof(usetup.name), 
                 "Smice Virtual Device %d", i);

        if (ioctl(fd, UI_DEV_SETUP, &usetup) == -1) {
            perror("ioctl UI_DEV_SETUP failed");
            close(fd);
            goto vdev_err;
        }

        if (ioctl(fd, UI_DEV_CREATE) == -1) {
            perror("ioctl UI_DEV_CREATE failed");
            close(fd);
            goto vdev_err;
        }

        strncpy(dst_devices[i].name, usetup.name, sizeof(dst_devices[i].name));
        dst_devices[i].name[sizeof(dst_devices[i].name)-1] = '\0';
        dst_devices[i].fd = fd;
    }

   /* On UI_DEV_CREATE the kernel will create the device node for this
    * device. We are inserting a pause here so that userspace has time
    * to detect, initialize the new device, and can start listening to
    * the event, otherwise it will not notice the event we are about
    * to send. */
    usleep(100000);
    return 1;

vdev_err:
    for (int j = 0; j < i; j++) {
        ioctl(dst_devices[j].fd, UI_DEV_DESTROY);
        close(dst_devices[j].fd);
    }

   return 0;
}

/* Destroy and close the 'count' created virtual 'devices'. */
void destroyVirtualDevices(struct dev *devices, int count) {
    for (int i = 0; i < count; i++) {
        ioctl(devices[i].fd, UI_DEV_DESTROY);
        close(devices[i].fd);
    }
}

/* Read as many pending events as possible from all ready file descriptors 
 * of 'count' 'devices' and save them into 'events' buffer.
 * 'max_events' is the maximum capacity of the event array.
 * It waits for one of the 'count' device file descriptors to become ready. 
 * Return the total number of events successfully read, or -1 on error. */
int readEvents(struct dev *devices, int count, 
               struct dev_event *events, int max_events) 
{
    struct pollfd poll_fds[count];
    for (int i = 0; i < count; i++) {
        poll_fds[i] = (struct pollfd){
            .fd     = devices[i].fd,
            .events = POLLIN,
        };
    }

    int poll_status = poll(poll_fds, count, -1);
    if (poll_status <= 0) {
        return poll_status;
    }

    int events_read = 0;
    for (int i = 0; i < count; i++) {
        if (events_read >= max_events) break; /* event buffer is full */

        if (poll_fds[i].revents & POLLIN) {
            /* Read a whole block of events in a single system call */
            int free_events = max_events - events_read;
            struct input_event iebuf[free_events];

            ssize_t bytes_read = read(poll_fds[i].fd, &iebuf, sizeof(iebuf));
            if (bytes_read > 0) {
                int num_read = bytes_read / sizeof(struct input_event);
                for (int j = 0; j < num_read; j++) {
                    events[events_read].event = iebuf[j];
                    events[events_read].dev_index = i;
                    events_read++;
                }
            } else if (bytes_read < 0) {
                /* Ignore EAGAIN/EWOULDBLOCK since we are in non-blocking 
                 * mode */
                if (errno != EAGAIN && errno != EWOULDBLOCK) {
                    perror("Error reading from input device");
                    return -1;
                }
            }
        }
    }

    return events_read;
}

/* Send an input event to the 'device'.
 * Return 1 if the event is successfully sent, 0 otherwise. */
int emitEvent(struct dev *device, struct input_event *ie) {
    if (write(device->fd, ie, sizeof(struct input_event)) == -1) {
        perror("Failed emitting event");
        return 0;
    }
    return 1;
}

/* Compute the Exponential Moving Average (EMA) of row data 'x' applied to 
 * the previous smoothing data series 's' with smoothing factor 'f'. 
 * Return the computed smoothed value. */
double expSmooth(double x, double s, float f) {
    return f * x + (1 - f) * s;
}

/* Show the program usage. */
void showUsage(const char *progname) {
    printf("Usage: %s [OPTIONS...]\n\n"
           "   -s FACTOR, --smooth-rate=FACTOR\n"
           "          set the movement smoothing level. Must be a value between\n"
           "          0.0 and 1.0. An higher value produce a smoother behavior.\n"
           "          (default: 0.80)\n\n"
           "   -a ACTION_LIST, --actions=ACTION_LIST\n"
           "          a comma-separated list of actions that trigger the\n"
           "          smoothing effect. Available actions:\n"
           "          'ALWAYS', 'LEFT-CLICK', 'RIGHT-CLICK',\n"
           "          'MIDDLE-CLICK', 'ON-TOUCH'\n"
           "          (default: 'LEFT-CLICK')\n\n"
           "          Note that the 'LEFT-CLICK', 'RIGHT-CLICK', 'MIDDLE-CLICK'\n"
           "          actions trigger on mice and on some trackpad devices.\n"
           "          Instead the 'ON-TOUCH' action triggers on trackpads,\n"
           "          tablets, etc.\n\n"
           "   -h, --help  Display this help message and exit.\n\n",
           progname);
}

/* Show the program help message on standard error. */
void showHelp(void) {
    fprintf(stderr, "Try `%s --help` for more information\n", smice.progname);
}

/* Parse comma-separated actions string.
 * Return the computed action bitmask or 0 on error. */
uint32_t parseActions(const char *str) {
    uint32_t mask = 0;
    char *actstr = strdup(str);
    if (actstr == NULL) return 0;

    char *tok = strtok(actstr, ",");
    while (tok != NULL) {
        if (strcmp(tok, "ALWAYS") == 0) {
            mask |= ACTION_ALWAYS;
        } else if (strcmp(tok, "LEFT-CLICK") == 0) {
            mask |= ACTION_LEFT_CLICK;
        } else if (strcmp(tok, "MIDDLE-CLICK") == 0) {
            mask |= ACTION_MIDDLE_CLICK;
        } else if (strcmp(tok, "RIGHT-CLICK") == 0) {
            mask |= ACTION_RIGHT_CLICK;
        } else if (strcmp(tok, "ON-TOUCH") == 0) {
            mask |= ACTION_ON_TOUCH;
        } else {
            fprintf(stderr, "Unrecognized action trigger `%s`\n", tok);
            showHelp();
            mask = 0;
            break;
        }

        tok = strtok(NULL, ",");
    }

    free(actstr);
    return mask;
}

int main(int argc, char **argv) {
    const char *progname = argv[0];
    smice.progname = progname;

    if (argc > 5) {
        fprintf(stderr, "Too many argument for the program\n");
        showHelp();
        return 1;
    }

    smice.smooth_rate = DEFAULT_SMOOTH_RATE;
    smice.config_actions = ACTION_LEFT_CLICK;
    smice.active_actions = 0;

    /* Parse arguments */
    for (int i = 1; i < argc; i++) {
        int moreargs = (i+1) < argc;
        if (strcmp(argv[i], "-s") == 0) {
            if (!moreargs) {
                fprintf(stderr, "%s option needs a value after it\n", argv[i]);
                showHelp();
                return 1;
            }

            i++;
            float smooth_rate = atof(argv[i]);
            if (smooth_rate >= 0.0f && smooth_rate <= 1.0f)
                smice.smooth_rate = smooth_rate;
        }
        else if (strncmp(argv[i], "--smooth-rate=", 14) == 0) {
            if (strlen(argv[i]+14) == 0) {
                fprintf(stderr, "%s argument needs a value\n", argv[i]);
                showHelp();
                return 1;
            }

            float smooth_rate = atof(argv[i]+14);
            if (smooth_rate >= 0.0f && smooth_rate <= 1.0f)
                smice.smooth_rate = smooth_rate;
        }
        else if (strcmp(argv[i], "-a") == 0) {
            if (!moreargs) {
                fprintf(stderr, "%s option needs a list of actions after it\n",
                        argv[i]);
                showHelp();
                return 1;
            }

            i++;
            uint32_t actions = parseActions(argv[i]);
            if (actions == 0) return 1;
            smice.config_actions = actions;
        }
        else if (strncmp(argv[i], "--actions=", 10) == 0) {
            if (strlen(argv[i]+10) == 0) {
                fprintf(stderr, "%s argument needs a list of actions\n", 
                        argv[i]);
                showHelp();
                return 1;
            }

            uint32_t actions = parseActions(argv[i] + 10);
            if (actions == 0) return 1;
            smice.config_actions = actions;
        }
        else if (strcmp(argv[i], "-h") == 0 ||
                 strcmp(argv[i], "--help") == 0) {
            showUsage(argv[0]);
            return 0;
        } else {
            fprintf(stderr, "%s: unrecognized option `%s`\n", 
                    progname, argv[i]);
            showHelp();
            return 1;
        }
    }

    /* Record termination signals to gracefully quit the event loop. */
    if (signal(SIGINT, sigHandler) == SIG_ERR) {
        perror("Error registering SIGINT handler");
        return 1;
    }
    if (signal(SIGTERM, sigHandler) == SIG_ERR) {
        perror("Error registering SIGTERM handler");
        return 1;
    }

    errno = 0;
    int device_count = getPointerDevices(smice.phy_devices, MAX_DEVICES);
    if (device_count == -1) {
        if (errno == EACCES) {
            fprintf(stderr, "Since %s files are proteced for security "
                    "reasons, run the program again with sudo: `sudo ", 
                    DEVICE_EVENT_PATH);
            for (int i = 0; i < argc; i++) {
                printf("%s", argv[i]);
                if (i < argc-1) printf(" ");
            }
            printf("`\n");
            return 1;
        }
    } else if (device_count == 0) {
        fprintf(stderr, "No mouse devices found\n");
        fprintf(stderr, "Please check /proc/bus/input/devices file to see "
                "if there are any mice device available (if the cat hasn't "
                "eaten them all)\n");
        return 1;
    }

    printf("Smooth rate:     %.3f\n",   smice.smooth_rate);
    printf("Trigger actions: [");
    uint32_t actions = smice.config_actions;
    while (actions != 0) {
        if (HAS_ACTION(actions, ACTION_ALWAYS)) {
            printf("ALWAYS");
            actions &= ~ACTION_ALWAYS;
        } else if (HAS_ACTION(actions, ACTION_LEFT_CLICK)) {
            printf("LEFT-CLICK");
            actions &= ~ACTION_LEFT_CLICK;
        } else if (HAS_ACTION(actions, ACTION_MIDDLE_CLICK)) {
            printf("MIDDLE-CLICK");
            actions &= ~ACTION_MIDDLE_CLICK;
        } else if (HAS_ACTION(actions, ACTION_RIGHT_CLICK)) {
            printf("RIGHT-CLICK");
            actions &= ~ACTION_RIGHT_CLICK;
        } else if (HAS_ACTION(actions, ACTION_ON_TOUCH)) {
            printf("ON-TOUCH");
            actions &= ~ACTION_ON_TOUCH;
        }

        if (actions != 0) printf(", ");
    }
    printf("]\n");

    printf("\n");
    printf("%s is listening the following %d devices:\n", 
           argv[0], device_count);
    for (int i = 0; i < device_count; i++) {
        printf("%s\n", smice.phy_devices[i].name);
    }
    printf("\n");
    printf("Press CTRL+C to safely quit the program\n");

    /* Grab control of the devices to hide them from the OS. */
    for (int i = 0; i < device_count; i++) {
        if (ioctl(smice.phy_devices[i].fd, EVIOCGRAB, 1) == -1) 
            perror("ioctl grab");
    }

    /* Create virtual devices that mirrors the physical grabbed ones */
    createVirtualDevices(smice.vir_devices, smice.phy_devices, device_count);

    /* Event loop */
    while (running) {
        errno = 0;
        int event_count = readEvents(smice.phy_devices, device_count, 
                                     smice.event_buf, EVENT_BUFFER_SIZE);
        if (event_count == -1) {
            /* check if a signal has been throw */ 
            if (errno != EINTR) perror("poll");
            break;
        }

        for (int e = 0; e < event_count; e++) {
            struct input_event ie = smice.event_buf[e].event;
            int dev_index = smice.event_buf[e].dev_index;

            /* Track current trigger actions states */
            if (ie.type == EV_KEY) {
                int button_flag = 0;
                if (ie.code == BTN_LEFT)   button_flag = ACTION_LEFT_CLICK;
                if (ie.code == BTN_MIDDLE) button_flag = ACTION_MIDDLE_CLICK;
                if (ie.code == BTN_RIGHT)  button_flag = ACTION_RIGHT_CLICK;
                if (ie.code == BTN_TOUCH)  button_flag = ACTION_ON_TOUCH;

                if (button_flag != 0) {
                    if (ie.value != 0) /* button pressed */
                        smice.active_actions |= button_flag;
                    else               /* button released */
                        smice.active_actions &= ~button_flag;
                }

                /* Catch finger/pen lift-off events to reset absolute
                 * initialization state */
                if (ie.code == BTN_TOUCH && ie.value == 0) {
                    smice.device_pos[dev_index].is_init = 0;
                }
            }

            int is_smooth_active = 
                HAS_ACTION(smice.config_actions, ACTION_ALWAYS) ||
                HAS_ACTION(smice.config_actions, smice.active_actions);

            /* Smooth relative mouse pointer movements */
            if (ie.type == EV_REL) {
                if (is_smooth_active) {
                    if (ie.code == REL_X) {
                        int smooth_val = expSmooth(ie.value, 
                                smice.device_pos[dev_index].x,
                                1-smice.smooth_rate);
                        smice.device_pos[dev_index].x = smooth_val;
                        ie.value = smooth_val;
                    }
                    else if (ie.code == REL_Y) {
                        int smooth_val = expSmooth(ie.value, 
                                smice.device_pos[dev_index].y,
                                1-smice.smooth_rate);
                        smice.device_pos[dev_index].y = smooth_val;
                        ie.value = smooth_val;
                    }
                } else {
                    if (ie.code == REL_X) smice.device_pos[dev_index].x = 0;
                    if (ie.code == REL_Y) smice.device_pos[dev_index].y = 0;
                }
            }
            /* Smooth absolute pointer movements */
            else if (ie.type == EV_ABS) {
                if (is_smooth_active) {
                    if (ie.code == ABS_X) {
                        int curr_pos = smice.device_pos[dev_index].x;

                        /* Initialize or handle massive jumps */
                        double diff = (ie.value > curr_pos) ? 
                            (ie.value - curr_pos) : (curr_pos - ie.value);
                        if (!smice.device_pos[dev_index].is_init || 
                                diff > 1000.0) {
                            smice.device_pos[dev_index].x = ie.value;
                        }

                        int smooth_val = expSmooth(ie.value,
                                smice.device_pos[dev_index].x,
                                1-smice.smooth_rate);
                        smice.device_pos[dev_index].x = smooth_val;
                        ie.value = smooth_val;
                    }
                    else if (ie.code == ABS_Y) {
                        int curr_pos = smice.device_pos[dev_index].y;

                        /* Initialize or handle massive jumps */
                        double diff = (ie.value > curr_pos) ? 
                            (ie.value - curr_pos) : (curr_pos - ie.value);
                        if (!smice.device_pos[dev_index].is_init || 
                                diff > 1000.0) {
                            smice.device_pos[dev_index].y = ie.value;
                        }

                        int smooth_val = expSmooth(ie.value,
                                smice.device_pos[dev_index].y,
                                1-smice.smooth_rate);
                        smice.device_pos[dev_index].y = smooth_val;
                        ie.value = smooth_val;
                    }
                } else {
                    if (ie.code == ABS_X) 
                        smice.device_pos[dev_index].x = ie.value;
                    if (ie.code == ABS_Y) 
                        smice.device_pos[dev_index].y = ie.value;
                }
            }
            else if (ie.type == EV_SYN && ie.code == SYN_REPORT) {
                /* Lock initialization only after the entire packet event
                 * is processed */
                smice.device_pos[dev_index].is_init = 1;
            }

            emitEvent(&smice.vir_devices[dev_index], &ie);
        }
    }

    /* Destroy virtual devices */
    destroyVirtualDevices(smice.vir_devices, device_count);

    /* Release control of the devices. */
    for (int i = 0; i < device_count; i++) {
        if (ioctl(smice.phy_devices[i].fd, EVIOCGRAB, 0) == -1) 
            perror("ioctl release");
    }

    printf("\n");
    printf("Input devices safely released\n");

    for (int i = 0; i < device_count; i++) {
        if (smice.phy_devices[i].fd != -1) {
            if (close(smice.phy_devices[i].fd) == -1) {
                error(0, errno, "Failed to close file descriptor %d", 
                      smice.phy_devices[i].fd);
            }
        }
    }

    return 0;
}
