#include <errno.h>
#include <error.h>
#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <linux/input.h>
#include <linux/uinput.h>
#include <sys/ioctl.h>

/* Absolute path to the file that contains a list of all registered 
 * input devices */
#define DEVICE_INPUT_PATH "/proc/bus/input/devices"

/* Absolute path to the directory that contains real-time input events 
 * generated by the kernel's evdev (event device) subsystem */
#define DEVICE_EVENT_PATH "/dev/input/"

/* Absolute path to the file that allows to create a virtual device */
#define VIRTUAL_DEVICE_PATH "/dev/uinput"

#define MAX_DEVICES 16       /* Maximum number of devices supported in 
                              * parallel */
#define DEVICE_NAME_SIZE 128 /* Maximum number of character in a device name */
#define EVENT_BUFFER_SIZE 64 /* Maximum number of events int the buffer */

/* Represent an active device in the evdev */
struct dev {
    char name[DEVICE_NAME_SIZE]; /* Name of the device */
    int fd; /* Event handler file descriptor associated to the device */
};

/* Represent the state of the instance of the program. */
struct smice {
    struct dev phy_devices[MAX_DEVICES]; /* File descriptors of physical
                                          * devices */
    struct dev vir_devices[MAX_DEVICES]; /* File descriptors of virtual
                                          * devices */
    struct dev_event {
        struct input_event event; /* Event */
        int dev_index;            /* Index of the device in 'phy_devices' 
                                   * array that generates the event */
    } event_buf[EVENT_BUFFER_SIZE]; /* Buffer of events generated by the
                                     * physical devices */
} smice;

static volatile int running = 1;

/* Catch the signal from the program and set 'running' to 0. */
void sigHandler(int signum) {
    (void)signum;
    running = 0;
}

/* Search for all the registered mouse devices in the system and fills the 
 * `devices` array for each of them.
 * The search ends when no more new mice are found or when 'max_mice' mice 
 * have been found.
 * Return the number of mice device found. 
 * It's up to the caller to close the open file descriptors. */
int getMouseDevices(struct dev *devices, int max_mice) {
    FILE *fp = fopen(DEVICE_INPUT_PATH, "r");
    if (fp == NULL) {
        perror("Failed to open " DEVICE_INPUT_PATH);
        return 0;
    }

    /* Read the devices file to search for the following pattern:
     *   N: Name="..."
     *   H: Handlers=mouseX eventY
     * where X and Y are intergers that indicate the mouse and its 
     * associated event handler rispectively. */
    char line[512];
    int count = 0;
    char devname[DEVICE_NAME_SIZE];
    while (fgets(line, sizeof(line), fp) && count < max_mice) {
        if (strncmp(line, "N: Name=\"", 9) == 0) {
            strncpy(devname, line+9, sizeof(devname));
            devname[sizeof(devname)-1] = '\0'; 

            /* Erase terminating " or \n char */
            char *c;
            if      ((c = strchr(devname, '\"')) != NULL) *c = '\0';
            else if ((c = strchr(devname, '\n')) != NULL) *c = '\0';
        }

        if (strncmp(line, "H: Handlers=", 12) == 0 &&
            strstr(line, "mouse") != NULL) {
            char *evstr = strstr(line, "event");
            if (evstr != NULL) {
                struct dev *device = &devices[count];
                strncpy(device->name, devname, sizeof(device->name));
                device->name[sizeof(device->name)-1] = '\0';
                devname[0] = '\0';

                /* Get the file descriptor of the event handler file */
                int evnum = atoi(evstr+5);
                char event_path[64];
                snprintf(event_path, sizeof(event_path), "%sevent%d", 
                         DEVICE_EVENT_PATH, evnum);

                int fd;
                if ((fd = open(event_path, O_RDONLY | O_NONBLOCK)) == -1) {
                    error(0, errno, "Failed to open %s", event_path);
                    continue;
                }
                device->fd = fd;

                count++;
            }
        }
    }

    fclose(fp);
    return count;
}

/* Create 'count' virtual mice.
 * Return 1 on success, 0 otherwise.
 * It's up to the caller to destroy the virtual devices and close the 
 * open file descriptors. */
int createVirtualMice(struct dev *devices, int count) {
    struct uinput_setup usetup;

    int i;
    for (i = 0; i < count; i++) {
        int fd = open(VIRTUAL_DEVICE_PATH, O_WRONLY | O_NONBLOCK);
        if (fd == -1) {
            perror("Failed to open " VIRTUAL_DEVICE_PATH);
            goto vmice_err;
        }

        /* Enable mouse button */
        ioctl(fd, UI_SET_EVBIT,  EV_KEY);
        ioctl(fd, UI_SET_KEYBIT, BTN_LEFT);
        ioctl(fd, UI_SET_KEYBIT, BTN_RIGHT);
        ioctl(fd, UI_SET_KEYBIT, BTN_MIDDLE);

        /* Enable mouse relative movement axes */
        ioctl(fd, UI_SET_EVBIT,  EV_REL);
        ioctl(fd, UI_SET_RELBIT, REL_X);
        ioctl(fd, UI_SET_RELBIT, REL_Y);
        ioctl(fd, UI_SET_RELBIT, REL_WHEEL);

        /* Configure device properties */
        memset(&usetup, 0, sizeof(usetup));
        usetup.id.bustype = BUS_USB;
        usetup.id.vendor  = 0xCAFE;      /* sample vendor ID */
        usetup.id.product = 0x0001 + i; /* unique product ID */
        snprintf(usetup.name, sizeof(usetup.name), "Smice Mouse %d", i);

        if (ioctl(fd, UI_DEV_SETUP, &usetup) == -1) {
            perror("ioctl UI_DEV_SETUP failed");
            close(fd);
            goto vmice_err;
        }

        if (ioctl(fd, UI_DEV_CREATE) == -1) {
            perror("ioctl UI_DEV_CREATE failed");
            close(fd);
            goto vmice_err;
        }

        strncpy(devices[i].name, usetup.name, sizeof(devices[i].name));
        devices[i].name[sizeof(devices[i].name)-1] = '\0';
        devices[i].fd = fd;
    }

   /* On UI_DEV_CREATE the kernel will create the device node for this
    * device. We are inserting a pause here so that userspace has time
    * to detect, initialize the new device, and can start listening to
    * the event, otherwise it will not notice the event we are about
    * to send. */
    usleep(100000);
    return 1;

vmice_err:
    for (int j = 0; j < i; j++) {
        ioctl(devices[j].fd, UI_DEV_DESTROY);
        close(devices[j].fd);
    }

   return 0;
}

/* Destroy and close the 'count' created virtual 'devices'. */
void destroyVirtualMice(struct dev *devices, int count) {
    for (int i = 0; i < count; i++) {
        ioctl(devices[i].fd, UI_DEV_DESTROY);
        close(devices[i].fd);
    }
}

/* Read as many pending events as possible from all ready file descriptors 
 * of 'count' 'devices' and save them into 'events' buffer.
 * 'max_events' is the maximum capacity of the event array.
 * It waits for one of the 'count' file descriptors to become ready. 
 * Return the total number of events successfully read, or a negative value
 * on error. */
int readEvents(struct dev *devices, int count, 
               struct dev_event *events, int max_events) 
{
    struct pollfd poll_fds[count];
    for (int i = 0; i < count; i++) {
        poll_fds[i] = (struct pollfd){
            .fd     = devices[i].fd,
            .events = POLLIN,
        };
    }

    int poll_status = poll(poll_fds, count, -1);
    if (poll_status <= 0) {
        if (poll_status == -1 && errno != EINTR) perror("poll");
        return poll_status;
    }

    int events_read = 0;
    for (int i = 0; i < count; i++) {
        if (events_read >= max_events) break; /* event buffer is full */

        if (poll_fds[i].revents & POLLIN) {
            /* Read a whole block of events in a single system call */
            int free_events = max_events - events_read;
            struct input_event iebuf[free_events];

            ssize_t bytes_read = read(poll_fds[i].fd, &iebuf, sizeof(iebuf));
            if (bytes_read > 0) {
                int num_read = bytes_read / sizeof(struct input_event);
                for (int j = 0; j < num_read; j++) {
                    events[events_read].event = iebuf[j];
                    events[events_read].dev_index = i;
                    events_read++;
                }
            } else if (bytes_read < 0) {
                /* Ignore EAGAIN/EWOULDBLOCK since we are in non-blocking 
                 * mode */
                if (errno != EAGAIN && errno != EWOULDBLOCK) {
                    perror("Error reading from input device");
                    return -1;
                }
            }
        }
    }

    return events_read;
}

/* Send an input event to the 'fd' file descriptor. 
 * Return 1 if the event is successfully sent, 0 otherwise. */
int emitEvent(int fd, struct input_event *ie) {
    if (write(fd, ie, sizeof(struct input_event)) == -1) {
        perror("Failed emitting event");
        return 0;
    }
    return 1;
}

int main(int argc, char **argv) {
    (void)argc;

    /* Record termination signals to gracefully quit the event loop. */
    if (signal(SIGINT, sigHandler) == SIG_ERR) {
        perror("Error registering SIGINT handler");
        return 1;
    }
    if (signal(SIGTERM, sigHandler) == SIG_ERR) {
        perror("Error registering SIGTERM handler");
        return 1;
    }

    errno = 0;
    int mouse_count = getMouseDevices(smice.phy_devices, MAX_DEVICES);
    if (errno == EACCES) {
        fprintf(stderr, "Since %s files are proteced for security "
                "reasons, run the program again with `sudo`\n", 
                DEVICE_EVENT_PATH);
        return 1;
    } else if (mouse_count == 0) {
        fprintf(stderr, "No mouse devices found\n");
        fprintf(stderr, "Please check /proc/bus/input/devices file to see "
                "if there are any mice available (if the cat hasn't eaten "
                "them all)\n");
        return 1;
    }

    printf("%s is listening the following %d mice:\n", argv[0], mouse_count);
    for (int i = 0; i < mouse_count; i++) {
        printf("%s\n", smice.phy_devices[i].name);
    }
    printf("\n");
    printf("Press CTRL+C to safely quit the program\n");

    /* Grab control of the devices to hide them from the OS. */
    for (int i = 0; i < mouse_count; i++) {
        if (ioctl(smice.phy_devices[i].fd, EVIOCGRAB, 1) == -1) 
            perror("ioctl grab");
    }

    /* Create virtual mice that mirrors the grabbed ones */
    createVirtualMice(smice.vir_devices, mouse_count);

    /* Event loop */
    while (running) {
        int event_count = readEvents(smice.phy_devices, mouse_count, 
                                     smice.event_buf, EVENT_BUFFER_SIZE);
        if (event_count < 0) break;

        for (int e = 0; e < event_count; e++) {
            struct input_event ie = smice.event_buf[e].event;
            int dev_index = smice.event_buf[e].dev_index;
            emitEvent(smice.vir_devices[dev_index].fd, &ie);

            printf("dev:%d, time %ld.%06ld\ttype %d\tcode %d\tvalue %d\n",
                   dev_index, ie.time.tv_sec, ie.time.tv_usec, ie.type, 
                   ie.code, ie.value);
        }
    }

    /* Destroy virtual mice */
    destroyVirtualMice(smice.vir_devices, mouse_count);

    /* Release control of the devices. */
    for (int i = 0; i < mouse_count; i++) {
        if (ioctl(smice.phy_devices[i].fd, EVIOCGRAB, 0) == -1) 
            perror("ioctl release");
    }

    printf("\n");
    printf("Input devices safely released\n");

    for (int i = 0; i < mouse_count; i++) {
        if (smice.phy_devices[i].fd != -1) {
            if (close(smice.phy_devices[i].fd) == -1) {
                error(0, errno, "Failed to close file descriptor %d", 
                      smice.phy_devices[i].fd);
            }
        }
    }

    return 0;
}
