#include <errno.h>
#include <error.h>
#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <linux/input.h>
#include <linux/uinput.h>
#include <sys/ioctl.h>

/* Absolute path to the file that contains a list of all registered 
 * input devices */
#define DEVICE_INPUT_PATH "/proc/bus/input/devices"

/* Absolute path to the directory that contains real-time input events 
 * generated by the kernel's evdev (event device) subsystem */
#define DEVICE_EVENT_PATH "/dev/input/"

/* Absolute path to the file that allows to create a virtual device */
#define VIRTUAL_DEVICE_PATH "/dev/uinput"

#define MAX_DEVICES 16       /* Maximum number of devices supported in 
                              * parallel */
#define DEVICE_NAME_SIZE 128 /* Maximum number of character in a device name */
#define EVENT_BUFFER_SIZE 64 /* Maximum number of events int the buffer */

/* Represent the weight applied to a stream of data for the smoothing 
 * algorithm */
#define SMOOTH_FACTOR 0.20

/* Number of bits in a single unsigned long integer */
#define BITS_PER_LONG (sizeof(unsigned long) * 8)

/* Determine the number of unsigned long elements required to hold 'x' bits */
#define NBITS(x) (((x) - 1)/BITS_PER_LONG+1)

/* Return 1 if the specified 'bit' is set in the 'array', 0 otherwise */
#define TEST_BIT(bit, array) \
    ((array[(bit) / BITS_PER_LONG] >> ((bit) % BITS_PER_LONG)) & 1)

/* Represent an active device in the evdev */
struct dev {
    char name[DEVICE_NAME_SIZE]; /* Name of the device */
    int fd; /* Event handler file descriptor associated to the device */
};

/* Represent the state of the instance of the program. */
struct smice {
    struct dev phy_devices[MAX_DEVICES]; /* File descriptors of physical
                                          * devices */
    struct dev vir_devices[MAX_DEVICES]; /* File descriptors of virtual
                                          * devices */
    struct dev_event {
        struct input_event event; /* Event */
        int dev_index;            /* Index of the device in 'phy_devices' 
                                   * array that generates the event */
    } event_buf[EVENT_BUFFER_SIZE]; /* Buffer of events generated by the
                                     * physical devices */
    struct dev_pos {
        double x;
        double y;
        int is_init; /* Flag to track initialization state for absolute
                      * coordinate. 
                      * 0 (finger/per lifted) if the device position will 
                      * snap directly to the raw hardware input
                      * 1 if the device position is part of an history 
                      * position state */
    } device_pos[MAX_DEVICES];      /* Track the average history value of 
                                     * positions for each device */
} smice;

static volatile int running = 1;

/* Catch the signal from the program and set 'running' to 0. */
void sigHandler(int signum) {
    (void)signum;
    running = 0;
}

/* Search for all the registered pointinga devices (mice, trackpads, tablets) 
 * and fills the `devices` array for each of them.
 * The search ends when no more new devices are found or when 'max_devices' 
 * devices have been found.
 * Return the number of devices found or -1 if an error occurs.
 * It's up to the caller to close the open file descriptors. */
int getPointerDevices(struct dev *devices, int max_devices) {
    FILE *fp = fopen(DEVICE_INPUT_PATH, "r");
    if (fp == NULL) {
        perror("Failed to open " DEVICE_INPUT_PATH);
        return -1;
    }

    /* Read the devices file to search for the following pattern:
     *   N: Name="..."
     *   H: Handlers=mouseX eventY
     * where X and Y are intergers that indicate the mouse and its 
     * associated event handler rispectively. */
    char line[512];
    int count = 0;
    char devname[DEVICE_NAME_SIZE];
    while (fgets(line, sizeof(line), fp) && count < max_devices) {
        if (strncmp(line, "N: Name=\"", 9) == 0) {
            strncpy(devname, line+9, sizeof(devname));
            devname[sizeof(devname)-1] = '\0'; 

            /* Erase terminating " or \n char */
            char *c;
            if      ((c = strchr(devname, '\"')) != NULL) *c = '\0';
            else if ((c = strchr(devname, '\n')) != NULL) *c = '\0';
        }

        if (strncmp(line, "H: Handlers=", 12) == 0) {
            char *evstr = strstr(line, "event");
            if (evstr != NULL) {
                /* Get the event handler file of the device */
                int evnum = atoi(evstr+5);
                char event_path[64];
                snprintf(event_path, sizeof(event_path), "%sevent%d", 
                         DEVICE_EVENT_PATH, evnum);

                int fd;
                if ((fd = open(event_path, O_RDONLY | O_NONBLOCK)) == -1) {
                    error(0, errno, "Failed to open %s", event_path);
                    goto efile_err;
                }

                /* Query the device capabilities to check if it's a cursor
                 * controller */
                unsigned long ev_bits[NBITS(EV_MAX)] = {0};
                int is_pointer = 0;

                if (ioctl(fd, EVIOCGBIT(0, sizeof(ev_bits)), ev_bits) >= 0) {
                    /* Check for relative pointer */
                    if (TEST_BIT(EV_REL, ev_bits)) {
                        unsigned long rel_bits[NBITS(REL_MAX)] = {0};
                        ioctl(fd, EVIOCGBIT(EV_REL, sizeof(rel_bits)), 
                              rel_bits);
                        if (TEST_BIT(REL_X, rel_bits) && 
                            TEST_BIT(REL_Y, rel_bits)) is_pointer = 1;
                    }
                    /* Check for absolute pointer */
                    if (!is_pointer && TEST_BIT(EV_ABS, ev_bits)) {
                        unsigned long abs_bits[NBITS(ABS_MAX)] = {0};
                        ioctl(fd, EVIOCGBIT(EV_ABS, sizeof(abs_bits)),
                              abs_bits);
                        if (TEST_BIT(ABS_X, abs_bits) && 
                            TEST_BIT(ABS_Y, abs_bits)) is_pointer = 1;
                    }
                }

                if (!is_pointer) {
                    devname[0] = '\0';
                    close(fd);
                    continue;
                }

                struct dev *device = &devices[count];
                strncpy(device->name, devname, sizeof(device->name));
                device->name[sizeof(device->name)-1] = '\0';
                device->fd = fd;
                devname[0] = '\0';

                count++;
            }
        }
    }

    fclose(fp);
    return count;

efile_err:
    for (int j = 0; j < count; j++) {
        close(devices[j].fd);
    }

    return -1;
}

/* Create 'count' virtual devices that clone the capabilities of the 
 * 'count' 'src_devices'.
 * Return 1 on success, 0 otherwise.
 * It's up to the caller to destroy the created virtual devices. */
int createVirtualDevices(struct dev *dst_devices, struct dev *src_devices, 
                         int count) 
{
    struct uinput_setup usetup;

    int i;
    for (i = 0; i < count; i++) {
        int src_fd = src_devices[i].fd;
        int fd = open(VIRTUAL_DEVICE_PATH, O_WRONLY | O_NONBLOCK);
        if (fd == -1) {
            perror("Failed to open " VIRTUAL_DEVICE_PATH);
            goto vdev_err;
        }

        /* Fetch main event types supported by the physical hardware */
        unsigned long ev_bits[NBITS(EV_MAX)] = {0};
        if (ioctl(src_fd, EVIOCGBIT(0, sizeof(ev_bits)), ev_bits) == -1) {
            perror("ioctl EVIOCGBIT failed");
            close(fd);
            goto vdev_err;
        }

        /* Clone buttons and keys */
        if (TEST_BIT(EV_KEY, ev_bits)) {
            ioctl(fd, UI_SET_EVBIT, EV_KEY);
            unsigned long key_bits[NBITS(KEY_MAX)] = {0};
            ioctl(src_fd, EVIOCGBIT(EV_KEY, sizeof(key_bits)), key_bits);
            for (int k = 0; k < KEY_MAX; k++) {
                if (TEST_BIT(k, key_bits)) {
                    ioctl(fd, UI_SET_KEYBIT, k);
                }
            }
        }

        /* Clone relative axis */
        if (TEST_BIT(EV_REL, ev_bits)) {
            ioctl(fd, UI_SET_EVBIT, EV_REL);
            unsigned long rel_bits[NBITS(REL_MAX)] = {0};
            ioctl(src_fd, EVIOCGBIT(EV_REL, sizeof(rel_bits)), rel_bits);
            for (int r = 0; r < REL_MAX; r++) {
                if (TEST_BIT(r, rel_bits)) {
                    ioctl(fd, UI_SET_RELBIT, r);
                }
            }
        }

        /* Clone absolute axis */
        if (TEST_BIT(EV_ABS, ev_bits)) {
            ioctl(fd, UI_SET_EVBIT, EV_ABS);
            unsigned long abs_bits[NBITS(ABS_MAX)] = {0};
            ioctl(src_fd, EVIOCGBIT(EV_ABS, sizeof(abs_bits)), abs_bits);
            for (int a = 0; a < ABS_MAX; a++) {
                if (TEST_BIT(a, abs_bits)) {
                    ioctl(fd, UI_SET_ABSBIT, a);

                    /* Important: Absolute devices must sync dimensions 
                     * with the kernel */
                    struct uinput_abs_setup abs_setup;
                    memset(&abs_setup, 0, sizeof(abs_setup));
                    abs_setup.code = a;
                    if (ioctl(src_fd, EVIOCGABS(a), &abs_setup.absinfo) >= 0) {
                        ioctl(fd, UI_ABS_SETUP, &abs_setup);
                    }
                }
            }
        }

        /* Configure device properties */
        memset(&usetup, 0, sizeof(usetup));
        usetup.id.bustype = BUS_USB;
        usetup.id.vendor  = 0xCAFE;      /* sample vendor ID */
        usetup.id.product = 0x0001 + i; /* unique product ID */
        snprintf(usetup.name, sizeof(usetup.name), 
                 "Smice Virtual Device %d", i);

        if (ioctl(fd, UI_DEV_SETUP, &usetup) == -1) {
            perror("ioctl UI_DEV_SETUP failed");
            close(fd);
            goto vdev_err;
        }

        if (ioctl(fd, UI_DEV_CREATE) == -1) {
            perror("ioctl UI_DEV_CREATE failed");
            close(fd);
            goto vdev_err;
        }

        strncpy(dst_devices[i].name, usetup.name, sizeof(dst_devices[i].name));
        dst_devices[i].name[sizeof(dst_devices[i].name)-1] = '\0';
        dst_devices[i].fd = fd;
    }

   /* On UI_DEV_CREATE the kernel will create the device node for this
    * device. We are inserting a pause here so that userspace has time
    * to detect, initialize the new device, and can start listening to
    * the event, otherwise it will not notice the event we are about
    * to send. */
    usleep(100000);
    return 1;

vdev_err:
    for (int j = 0; j < i; j++) {
        ioctl(dst_devices[j].fd, UI_DEV_DESTROY);
        close(dst_devices[j].fd);
    }

   return 0;
}

/* Destroy and close the 'count' created virtual 'devices'. */
void destroyVirtualDevices(struct dev *devices, int count) {
    for (int i = 0; i < count; i++) {
        ioctl(devices[i].fd, UI_DEV_DESTROY);
        close(devices[i].fd);
    }
}

/* Read as many pending events as possible from all ready file descriptors 
 * of 'count' 'devices' and save them into 'events' buffer.
 * 'max_events' is the maximum capacity of the event array.
 * It waits for one of the 'count' device file descriptors to become ready. 
 * Return the total number of events successfully read, or -1 on error. */
int readEvents(struct dev *devices, int count, 
               struct dev_event *events, int max_events) 
{
    struct pollfd poll_fds[count];
    for (int i = 0; i < count; i++) {
        poll_fds[i] = (struct pollfd){
            .fd     = devices[i].fd,
            .events = POLLIN,
        };
    }

    int poll_status = poll(poll_fds, count, -1);
    if (poll_status <= 0) {
        return poll_status;
    }

    int events_read = 0;
    for (int i = 0; i < count; i++) {
        if (events_read >= max_events) break; /* event buffer is full */

        if (poll_fds[i].revents & POLLIN) {
            /* Read a whole block of events in a single system call */
            int free_events = max_events - events_read;
            struct input_event iebuf[free_events];

            ssize_t bytes_read = read(poll_fds[i].fd, &iebuf, sizeof(iebuf));
            if (bytes_read > 0) {
                int num_read = bytes_read / sizeof(struct input_event);
                for (int j = 0; j < num_read; j++) {
                    events[events_read].event = iebuf[j];
                    events[events_read].dev_index = i;
                    events_read++;
                }
            } else if (bytes_read < 0) {
                /* Ignore EAGAIN/EWOULDBLOCK since we are in non-blocking 
                 * mode */
                if (errno != EAGAIN && errno != EWOULDBLOCK) {
                    perror("Error reading from input device");
                    return -1;
                }
            }
        }
    }

    return events_read;
}

/* Send an input event to the 'device'.
 * Return 1 if the event is successfully sent, 0 otherwise. */
int emitEvent(struct dev *device, struct input_event *ie) {
    if (write(device->fd, ie, sizeof(struct input_event)) == -1) {
        perror("Failed emitting event");
        return 0;
    }
    return 1;
}

/* Compute the Exponential Moving Average (EMA) of row data 'x' applied to 
 * the prevoius smoothing data series 's'. 
 * Return the computed smoothed value. */
double expSmooth(double x, double s) {
    return SMOOTH_FACTOR * x + (1 - SMOOTH_FACTOR) * s;
}

int main(int argc, char **argv) {
    (void)argc;

    /* Record termination signals to gracefully quit the event loop. */
    if (signal(SIGINT, sigHandler) == SIG_ERR) {
        perror("Error registering SIGINT handler");
        return 1;
    }
    if (signal(SIGTERM, sigHandler) == SIG_ERR) {
        perror("Error registering SIGTERM handler");
        return 1;
    }

    errno = 0;
    int device_count = getPointerDevices(smice.phy_devices, MAX_DEVICES);
    if (device_count == -1) {
        if (errno == EACCES) {
            fprintf(stderr, "Since %s files are proteced for security "
                    "reasons, run the program again with `sudo`\n", 
                    DEVICE_EVENT_PATH);
            return 1;
        }
    } else if (device_count == 0) {
        fprintf(stderr, "No mouse devices found\n");
        fprintf(stderr, "Please check /proc/bus/input/devices file to see "
                "if there are any mice device available (if the cat hasn't "
                "eaten them all)\n");
        return 1;
    }

    printf("%s is listening the following %d devices:\n", 
           argv[0], device_count);
    for (int i = 0; i < device_count; i++) {
        printf("%s\n", smice.phy_devices[i].name);
    }
    printf("\n");
    printf("Press CTRL+C to safely quit the program\n");

    /* Grab control of the devices to hide them from the OS. */
    for (int i = 0; i < device_count; i++) {
        if (ioctl(smice.phy_devices[i].fd, EVIOCGRAB, 1) == -1) 
            perror("ioctl grab");
    }

    /* Create virtual devices that mirrors the physical grabbed ones */
    createVirtualDevices(smice.vir_devices, smice.phy_devices, device_count);

    /* Event loop */
    while (running) {
        errno = 0;
        int event_count = readEvents(smice.phy_devices, device_count, 
                                     smice.event_buf, EVENT_BUFFER_SIZE);
        if (event_count == -1) {
            /* check if a signal has been throw */ 
            if (errno != EINTR) perror("poll");
            break;
        }

        for (int e = 0; e < event_count; e++) {
            struct input_event ie = smice.event_buf[e].event;
            int dev_index = smice.event_buf[e].dev_index;

            /* Catch finger/pen lift-off events to reset absolute
             * initialization state */
            if (ie.type == EV_KEY && ie.code == BTN_TOUCH) {
                if (ie.value == 0) {
                    smice.device_pos[dev_index].is_init = 0;
                }
            }

            /* Smooth relative mouse pointer movements */
            if (ie.type == EV_REL) {
                if (ie.code == REL_X) {
                    int smooth_val = expSmooth(ie.value, 
                                               smice.device_pos[dev_index].x);
                    smice.device_pos[dev_index].x = smooth_val;
                    ie.value = smooth_val;
                }
                else if (ie.code == REL_Y) {
                    int smooth_val = expSmooth(ie.value, 
                                               smice.device_pos[dev_index].y);
                    smice.device_pos[dev_index].y = smooth_val;
                    ie.value = smooth_val;
                }
            }
            /* Smooth absolute pointer movements */
            else if (ie.type == EV_ABS) {
                if (ie.code == ABS_X) {
                    int curr_pos = smice.device_pos[dev_index].x;

                    /* Initialize or handle massive jumps */
                    double diff = (ie.value > curr_pos) ? 
                        (ie.value - curr_pos) : (curr_pos - ie.value);
                    if (!smice.device_pos[dev_index].is_init || 
                        diff > 1000.0) {
                        smice.device_pos[dev_index].x = ie.value;
                    }

                    int smooth_val = expSmooth(ie.value,
                                               smice.device_pos[dev_index].x);
                    smice.device_pos[dev_index].x = smooth_val;
                    ie.value = smooth_val;
                }
                else if (ie.code == ABS_Y) {
                    int curr_pos = smice.device_pos[dev_index].y;

                    /* Initialize or handle massive jumps */
                    double diff = (ie.value > curr_pos) ? 
                        (ie.value - curr_pos) : (curr_pos - ie.value);
                    if (!smice.device_pos[dev_index].is_init || 
                        diff > 1000.0) {
                        smice.device_pos[dev_index].y = ie.value;
                    }

                    int smooth_val = expSmooth(ie.value,
                                               smice.device_pos[dev_index].y);
                    smice.device_pos[dev_index].y = smooth_val;
                    ie.value = smooth_val;
                }
            }
            else if (ie.type == EV_SYN && ie.code == SYN_REPORT) {
                /* Lock initialization only after the entire packet event
                 * is processed */
                smice.device_pos[dev_index].is_init = 1;
            }

            emitEvent(&smice.vir_devices[dev_index], &ie);

            printf("dev:%d  time %ld.%06ld  type %d  code %d  value %d\n",
                   dev_index, ie.time.tv_sec, ie.time.tv_usec, ie.type, 
                   ie.code, ie.value);
        }
    }

    /* Destroy virtual devices */
    destroyVirtualDevices(smice.vir_devices, device_count);

    /* Release control of the devices. */
    for (int i = 0; i < device_count; i++) {
        if (ioctl(smice.phy_devices[i].fd, EVIOCGRAB, 0) == -1) 
            perror("ioctl release");
    }

    printf("\n");
    printf("Input devices safely released\n");

    for (int i = 0; i < device_count; i++) {
        if (smice.phy_devices[i].fd != -1) {
            if (close(smice.phy_devices[i].fd) == -1) {
                error(0, errno, "Failed to close file descriptor %d", 
                      smice.phy_devices[i].fd);
            }
        }
    }

    return 0;
}
